# DO NOT EDIT THIS FILE!
#
# Python module Info__POA generated by omniidl

import omniORB
omniORB.updateModule("Info__POA")

# ** 1. Stub files contributing to this module
import raster_info_idl

# ** 2. Sub-modules

# ** 3. End
