# DO NOT EDIT THIS FILE!
#
# Python module Geo generated by omniidl

import omniORB
omniORB.updateModule("Geo")

# ** 1. Stub files contributing to this module
import geo_idl

# ** 2. Sub-modules

# ** 3. End
