module Projection {
	typedef float latitude;
	typedef float longitude;
	typedef float azimuth;
	typedef float distance;
	typedef short number_of_points;

	typedef string<1024> projection_name;
	typedef string<1024> projection_desc;

	typedef string<1024> ellipsoid_name;
	typedef string<1024> ellipsoid_desc;
	
	typedef string<1024> input_projection;
	typedef string<1024> output_projection;


	struct Fwd_transformation {
		latitude end_latitude;
		longitude end_longitude;
		azimuth back_azimuth;
	};

	struct Inv_transformation {
		azimuth trans_azimuth;
		azimuth back_azimuth;
		distance dist;
	};

	struct Npt {
		longitude end_longitude;
		latitude end_latitude;
	};

	struct Proj {
		projection_name proj_name;
		projection_desc proj_desc;
	};

	struct Ellipsoid {
		ellipsoid_name ellps_name;
		ellipsoid_desc ellps_desc;
	};

	struct Coordinates {
		float x2;
		float y2;
		float z2;
	};

	typedef sequence<Npt> Npts;
	typedef sequence<Proj> Proj_list;
	typedef sequence<Ellipsoid> Ellipsoid_list;

	exception ArgumentsNotInOrder {
		string reason;
	};

	interface Geodetic {

		//get_fwd_transformation - Returns longitudes, latitudes and back azimuths 
		//of terminus points given longitudes (lons) and latitudes (lats) of initial points, 
		//plus forward azimuths (az) and distances (dist).

		Fwd_transformation get_fwd_transformation(in longitude lons, in latitude lats, in azimuth az, in distance dist)
			raises (ArgumentsNotInOrder);

		//get_inv_transformation - Returns forward and back azimuths, plus distances between 
		//initial points (specified by lons1, lats1) and terminus points (specified by lons2, lats2).

		Inv_transformation get_inv_transformation(in longitude lons1, in latitude lats1, in longitude lons2, in latitude lats2)
			raises (ArgumentsNotInOrder);

		//Given a single initial point and terminus point (specified by python floats lon1,lat1 and lon2,lat2), 
		//returns a list of longitude/latitude pairs describing npts equally spaced intermediate 
		//points along the geodesic between the initial and terminus points.

		Npts get_intermediate_points(in longitude lons1, in latitude lats1, in longitude lons2, in latitude lats2, in number_of_points nop )
			raises (ArgumentsNotInOrder);

		//Function get_projection_list returns a list of available projection. The function takes no input parameters.

		Proj_list get_projection_list();

		//Function get_projection_list returns a list of available ellipsoid. The function takes no input parameters.

		Ellipsoid_list get_ellipsoid_list();

		//transform_coordinate_systems - Transforms points between two coordinate systems defined by the Proj instances p1 (Input_projection) and 
		//p2 (Output_projection).
		//The points x1,y1,z1 in the coordinate system defined by p1 are transformed to x2,y2,z2 in the coordinate system defined by p2.

		Coordinates transform_coordinate_systems(in input_projection in_projection, in output_projection out_projection, in float x1, 
							in float y1, in float z1, in string ellipsoide) raises (ArgumentsNotInOrder); 
	};
};
