# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geo.ui'
#
# Created: Thu Jul 26 13:28:33 2012
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys
import os
sys.path.append("..")
sys.path.append("../../logger")
sys.path.append("../../../interfaces/geo")

from Client import Client

class Ui_GeoBasic(Client):
    def setupUi(self, GeoBasic):
        GeoBasic.setObjectName("GeoBasic")
        GeoBasic.resize(890, 435)
        GeoBasic.setFixedHeight(435)
        GeoBasic.setFixedWidth(890)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(self.confIconsDir+'1344067877_Calculator.ico'), QtGui.QIcon.Normal, QtGui.QIcon.On)
        GeoBasic.setWindowIcon(icon)
        self.widgetTab = QtGui.QTabWidget(GeoBasic)
        self.widgetTab.setGeometry(QtCore.QRect(0, 0, 891, 391))
        self.widgetTab.setMinimumSize(QtCore.QSize(891, 0))
        self.widgetTab.setMaximumSize(QtCore.QSize(891, 16777215))
        self.widgetTab.setTabPosition(QtGui.QTabWidget.North)
        self.widgetTab.setTabShape(QtGui.QTabWidget.Rounded)
        self.widgetTab.setTabsClosable(False)
        self.widgetTab.setObjectName("widgetTab")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 381, 321))
        self.groupBox.setObjectName("groupBox")
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 89, 17))
        self.label.setObjectName("label")
        self.frame_3 = QtGui.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_2.setObjectName("label_2")
        self.hav_s_lat_input = QtGui.QLineEdit(self.frame_3)
        self.hav_s_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.hav_s_lat_input.setObjectName("hav_s_lat_input")
        self.hav_s_lon_input = QtGui.QLineEdit(self.frame_3)
        self.hav_s_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.hav_s_lon_input.setObjectName("hav_s_lon_input")
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.label_4.setObjectName("label_4")
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(10, 190, 351, 81))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtGui.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_6.setObjectName("label_6")
        self.hav_d_lat_input = QtGui.QLineEdit(self.frame_4)
        self.hav_d_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.hav_d_lat_input.setObjectName("hav_d_lat_input")
        self.hav_d_lon_input = QtGui.QLineEdit(self.frame_4)
        self.hav_d_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.hav_d_lon_input.setObjectName("hav_d_lon_input")
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(480, 10, 381, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.frame_2 = QtGui.QFrame(self.groupBox_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.hav_output = QtGui.QTextEdit(self.frame_2)
        self.hav_output.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.hav_output.setObjectName("hav_output")
        self.hav_ok_btn = QtGui.QPushButton(self.frame_2)
        self.hav_ok_btn.setGeometry(QtCore.QRect(250, 260, 91, 27))
        self.hav_ok_btn.setObjectName("hav_ok_btn")
        self.hav_clear_btn = QtGui.QPushButton(self.frame_2)
        self.hav_clear_btn.setGeometry(QtCore.QRect(30, 260, 91, 27))
        self.hav_clear_btn.setObjectName("hav_clear_btn")
        self.widgetTab.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 10, 381, 321))
        self.groupBox_3.setObjectName("groupBox_3")
        self.frame_5 = QtGui.QFrame(self.groupBox_3)
        self.frame_5.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setLineWidth(1)
        self.frame_5.setObjectName("frame_5")
        self.label_7 = QtGui.QLabel(self.frame_5)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 89, 17))
        self.label_7.setObjectName("label_7")
        self.frame_6 = QtGui.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_8 = QtGui.QLabel(self.frame_6)
        self.label_8.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtGui.QLabel(self.frame_6)
        self.label_9.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_9.setObjectName("label_9")
        self.sloc_s_lat_input = QtGui.QLineEdit(self.frame_6)
        self.sloc_s_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.sloc_s_lat_input.setObjectName("sloc_s_lat_input")
        self.sloc_s_lon_input = QtGui.QLineEdit(self.frame_6)
        self.sloc_s_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.sloc_s_lon_input.setObjectName("sloc_s_lon_input")
        self.label_10 = QtGui.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.label_10.setObjectName("label_10")
        self.frame_7 = QtGui.QFrame(self.frame_5)
        self.frame_7.setGeometry(QtCore.QRect(10, 190, 351, 81))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_11 = QtGui.QLabel(self.frame_7)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtGui.QLabel(self.frame_7)
        self.label_12.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_12.setObjectName("label_12")
        self.sloc_d_lat_input = QtGui.QLineEdit(self.frame_7)
        self.sloc_d_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.sloc_d_lat_input.setObjectName("sloc_d_lat_input")
        self.sloc_d_lon_input = QtGui.QLineEdit(self.frame_7)
        self.sloc_d_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.sloc_d_lon_input.setObjectName("sloc_d_lon_input")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(480, 10, 381, 321))
        self.groupBox_4.setObjectName("groupBox_4")
        self.frame_8 = QtGui.QFrame(self.groupBox_4)
        self.frame_8.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.sloc_output = QtGui.QTextEdit(self.frame_8)
        self.sloc_output.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.sloc_output.setObjectName("sloc_output")
        self.sloc_ok_btn = QtGui.QPushButton(self.frame_8)
        self.sloc_ok_btn.setGeometry(QtCore.QRect(250, 260, 91, 27))
        self.sloc_ok_btn.setObjectName("sloc_ok_btn")
        self.sloc_clear_btn = QtGui.QPushButton(self.frame_8)
        self.sloc_clear_btn.setGeometry(QtCore.QRect(30, 260, 91, 27))
        self.sloc_clear_btn.setObjectName("sloc_clear_btn")
        self.widgetTab.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 10, 381, 321))
        self.groupBox_5.setObjectName("groupBox_5")
        self.frame_9 = QtGui.QFrame(self.groupBox_5)
        self.frame_9.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setLineWidth(1)
        self.frame_9.setObjectName("frame_9")
        self.label_13 = QtGui.QLabel(self.frame_9)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 89, 17))
        self.label_13.setObjectName("label_13")
        self.frame_10 = QtGui.QFrame(self.frame_9)
        self.frame_10.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_14 = QtGui.QLabel(self.frame_10)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.frame_10)
        self.label_15.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_15.setObjectName("label_15")
        self.ib_s_lat_input = QtGui.QLineEdit(self.frame_10)
        self.ib_s_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.ib_s_lat_input.setObjectName("ib_s_lat_input")
        self.ib_s_lon_input = QtGui.QLineEdit(self.frame_10)
        self.ib_s_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.ib_s_lon_input.setObjectName("ib_s_lon_input")
        self.label_16 = QtGui.QLabel(self.frame_9)
        self.label_16.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.label_16.setObjectName("label_16")
        self.frame_11 = QtGui.QFrame(self.frame_9)
        self.frame_11.setGeometry(QtCore.QRect(10, 190, 351, 81))
        self.frame_11.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_17 = QtGui.QLabel(self.frame_11)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtGui.QLabel(self.frame_11)
        self.label_18.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_18.setObjectName("label_18")
        self.ib_d_lat_input = QtGui.QLineEdit(self.frame_11)
        self.ib_d_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.ib_d_lat_input.setObjectName("ib_d_lat_input")
        self.ib_d_lon_input = QtGui.QLineEdit(self.frame_11)
        self.ib_d_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.ib_d_lon_input.setObjectName("ib_d_lon_input")
        self.groupBox_6 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_6.setGeometry(QtCore.QRect(480, 10, 381, 321))
        self.groupBox_6.setObjectName("groupBox_6")
        self.frame_12 = QtGui.QFrame(self.groupBox_6)
        self.frame_12.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_12.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.ib_output = QtGui.QTextEdit(self.frame_12)
        self.ib_output.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.ib_output.setObjectName("ib_output")
        self.ib_ok_btn = QtGui.QPushButton(self.frame_12)
        self.ib_ok_btn.setGeometry(QtCore.QRect(250, 260, 91, 27))
        self.ib_ok_btn.setObjectName("ib_ok_btn")
        self.ib_clear_btn = QtGui.QPushButton(self.frame_12)
        self.ib_clear_btn.setGeometry(QtCore.QRect(30, 260, 91, 27))
        self.ib_clear_btn.setObjectName("ib_clear_btn")
        self.widgetTab.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_7 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_7.setGeometry(QtCore.QRect(480, 10, 381, 321))
        self.groupBox_7.setObjectName("groupBox_7")
        self.frame_13 = QtGui.QFrame(self.groupBox_7)
        self.frame_13.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.fb_output = QtGui.QTextEdit(self.frame_13)
        self.fb_output.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.fb_output.setObjectName("fb_output")
        self.fb_ok_btn = QtGui.QPushButton(self.frame_13)
        self.fb_ok_btn.setGeometry(QtCore.QRect(250, 260, 91, 27))
        self.fb_ok_btn.setObjectName("fb_ok_btn")
        self.fb_clear_btn = QtGui.QPushButton(self.frame_13)
        self.fb_clear_btn.setGeometry(QtCore.QRect(30, 260, 91, 27))
        self.fb_clear_btn.setObjectName("fb_clear_btn")
        self.groupBox_8 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(30, 10, 381, 321))
        self.groupBox_8.setObjectName("groupBox_8")
        self.frame_14 = QtGui.QFrame(self.groupBox_8)
        self.frame_14.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_14.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setLineWidth(1)
        self.frame_14.setObjectName("frame_14")
        self.label_19 = QtGui.QLabel(self.frame_14)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 89, 17))
        self.label_19.setObjectName("label_19")
        self.frame_15 = QtGui.QFrame(self.frame_14)
        self.frame_15.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_20 = QtGui.QLabel(self.frame_15)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.frame_15)
        self.label_21.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_21.setObjectName("label_21")
        self.fb_s_lat_input = QtGui.QLineEdit(self.frame_15)
        self.fb_s_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.fb_s_lat_input.setObjectName("fb_s_lat_input")
        self.fb_s_lon_input = QtGui.QLineEdit(self.frame_15)
        self.fb_s_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.fb_s_lon_input.setObjectName("fb_s_lon_input")
        self.label_22 = QtGui.QLabel(self.frame_14)
        self.label_22.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.label_22.setObjectName("label_22")
        self.frame_16 = QtGui.QFrame(self.frame_14)
        self.frame_16.setGeometry(QtCore.QRect(10, 190, 351, 81))
        self.frame_16.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.label_23 = QtGui.QLabel(self.frame_16)
        self.label_23.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtGui.QLabel(self.frame_16)
        self.label_24.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_24.setObjectName("label_24")
        self.fb_d_lat_input = QtGui.QLineEdit(self.frame_16)
        self.fb_d_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.fb_d_lat_input.setObjectName("fb_d_lat_input")
        self.fb_d_lon_input = QtGui.QLineEdit(self.frame_16)
        self.fb_d_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.fb_d_lon_input.setObjectName("fb_d_lon_input")
        self.widgetTab.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_9 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_9.setGeometry(QtCore.QRect(30, 10, 381, 321))
        self.groupBox_9.setObjectName("groupBox_9")
        self.frame_17 = QtGui.QFrame(self.groupBox_9)
        self.frame_17.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_17.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_17.setLineWidth(1)
        self.frame_17.setObjectName("frame_17")
        self.label_25 = QtGui.QLabel(self.frame_17)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 89, 17))
        self.label_25.setObjectName("label_25")
        self.frame_18 = QtGui.QFrame(self.frame_17)
        self.frame_18.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.frame_18.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_26 = QtGui.QLabel(self.frame_18)
        self.label_26.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtGui.QLabel(self.frame_18)
        self.label_27.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_27.setObjectName("label_27")
        self.mid_s_lat_input = QtGui.QLineEdit(self.frame_18)
        self.mid_s_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.mid_s_lat_input.setObjectName("mid_s_lat_input")
        self.mid_s_lon_input = QtGui.QLineEdit(self.frame_18)
        self.mid_s_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.mid_s_lon_input.setObjectName("mid_s_lon_input")
        self.label_28 = QtGui.QLabel(self.frame_17)
        self.label_28.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.label_28.setObjectName("label_28")
        self.frame_19 = QtGui.QFrame(self.frame_17)
        self.frame_19.setGeometry(QtCore.QRect(10, 190, 351, 81))
        self.frame_19.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.label_29 = QtGui.QLabel(self.frame_19)
        self.label_29.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtGui.QLabel(self.frame_19)
        self.label_30.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_30.setObjectName("label_30")
        self.mid_d_lat_input = QtGui.QLineEdit(self.frame_19)
        self.mid_d_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.mid_d_lat_input.setObjectName("mid_d_lat_input")
        self.mid_d_lon_input = QtGui.QLineEdit(self.frame_19)
        self.mid_d_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.mid_d_lon_input.setObjectName("mid_d_lon_input")
        self.groupBox_10 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_10.setGeometry(QtCore.QRect(480, 10, 381, 321))
        self.groupBox_10.setObjectName("groupBox_10")
        self.frame_20 = QtGui.QFrame(self.groupBox_10)
        self.frame_20.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_20.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.mid_output = QtGui.QTextEdit(self.frame_20)
        self.mid_output.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.mid_output.setObjectName("mid_output")
        self.mid_ok_btn = QtGui.QPushButton(self.frame_20)
        self.mid_ok_btn.setGeometry(QtCore.QRect(250, 260, 91, 27))
        self.mid_ok_btn.setObjectName("mid_ok_btn")
        self.mid_clear_btn = QtGui.QPushButton(self.frame_20)
        self.mid_clear_btn.setGeometry(QtCore.QRect(30, 260, 91, 27))
        self.mid_clear_btn.setObjectName("mid_clear_btn")
        self.widgetTab.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.groupBox_11 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_11.setGeometry(QtCore.QRect(480, 10, 381, 321))
        self.groupBox_11.setObjectName("groupBox_11")
        self.frame_21 = QtGui.QFrame(self.groupBox_11)
        self.frame_21.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_21.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.int_output = QtGui.QTextEdit(self.frame_21)
        self.int_output.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.int_output.setObjectName("int_output")
        self.int_ok_btn = QtGui.QPushButton(self.frame_21)
        self.int_ok_btn.setGeometry(QtCore.QRect(250, 260, 91, 27))
        self.int_ok_btn.setObjectName("int_ok_btn")
        self.int_clear_btn = QtGui.QPushButton(self.frame_21)
        self.int_clear_btn.setGeometry(QtCore.QRect(30, 260, 91, 27))
        self.int_clear_btn.setObjectName("int_clear_btn")
        self.groupBox_12 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 10, 381, 321))
        self.groupBox_12.setObjectName("groupBox_12")
        self.frame_22 = QtGui.QFrame(self.groupBox_12)
        self.frame_22.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_22.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_22.setLineWidth(1)
        self.frame_22.setObjectName("frame_22")
        self.label_31 = QtGui.QLabel(self.frame_22)
        self.label_31.setGeometry(QtCore.QRect(10, 10, 89, 17))
        self.label_31.setObjectName("label_31")
        self.frame_23 = QtGui.QFrame(self.frame_22)
        self.frame_23.setGeometry(QtCore.QRect(10, 40, 351, 101))
        self.frame_23.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.label_32 = QtGui.QLabel(self.frame_23)
        self.label_32.setGeometry(QtCore.QRect(10, 47, 71, 17))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtGui.QLabel(self.frame_23)
        self.label_33.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_33.setObjectName("label_33")
        self.int_s_lat_input = QtGui.QLineEdit(self.frame_23)
        self.int_s_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.int_s_lat_input.setObjectName("int_s_lat_input")
        self.int_s_lon_input = QtGui.QLineEdit(self.frame_23)
        self.int_s_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.int_s_lon_input.setObjectName("int_s_lon_input")
        self.label_37 = QtGui.QLabel(self.frame_23)
        self.label_37.setGeometry(QtCore.QRect(10, 80, 71, 17))
        self.label_37.setObjectName("label_37")
        self.int_s_bear_input = QtGui.QLineEdit(self.frame_23)
        self.int_s_bear_input.setGeometry(QtCore.QRect(200, 70, 131, 27))
        self.int_s_bear_input.setText("")
        self.int_s_bear_input.setObjectName("int_s_bear_input")
        self.label_34 = QtGui.QLabel(self.frame_22)
        self.label_34.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.label_34.setObjectName("label_34")
        self.frame_24 = QtGui.QFrame(self.frame_22)
        self.frame_24.setGeometry(QtCore.QRect(10, 190, 351, 101))
        self.frame_24.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.label_35 = QtGui.QLabel(self.frame_24)
        self.label_35.setGeometry(QtCore.QRect(10, 47, 71, 17))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtGui.QLabel(self.frame_24)
        self.label_36.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_36.setObjectName("label_36")
        self.int_d_lat_input = QtGui.QLineEdit(self.frame_24)
        self.int_d_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.int_d_lat_input.setObjectName("int_d_lat_input")
        self.int_d_lon_input = QtGui.QLineEdit(self.frame_24)
        self.int_d_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.int_d_lon_input.setObjectName("int_d_lon_input")
        self.label_38 = QtGui.QLabel(self.frame_24)
        self.label_38.setGeometry(QtCore.QRect(10, 80, 71, 17))
        self.label_38.setObjectName("label_38")
        self.int_d_bear_input = QtGui.QLineEdit(self.frame_24)
        self.int_d_bear_input.setGeometry(QtCore.QRect(200, 70, 131, 27))
        self.int_d_bear_input.setText("")
        self.int_d_bear_input.setObjectName("int_d_bear_input")
        self.widgetTab.addTab(self.tab_6, "")
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.groupBox_13 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_13.setGeometry(QtCore.QRect(480, 10, 381, 321))
        self.groupBox_13.setObjectName("groupBox_13")
        self.frame_25 = QtGui.QFrame(self.groupBox_13)
        self.frame_25.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_25.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.rdist_output = QtGui.QTextEdit(self.frame_25)
        self.rdist_output.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.rdist_output.setObjectName("rdist_output")
        self.rdist_ok_btn = QtGui.QPushButton(self.frame_25)
        self.rdist_ok_btn.setGeometry(QtCore.QRect(250, 260, 91, 27))
        self.rdist_ok_btn.setObjectName("rdist_ok_btn")
        self.rdist_clear_btn = QtGui.QPushButton(self.frame_25)
        self.rdist_clear_btn.setGeometry(QtCore.QRect(30, 260, 91, 27))
        self.rdist_clear_btn.setObjectName("rdist_clear_btn")
        self.groupBox_14 = QtGui.QGroupBox(self.tab_7)
        self.groupBox_14.setGeometry(QtCore.QRect(30, 10, 381, 321))
        self.groupBox_14.setObjectName("groupBox_14")
        self.frame_26 = QtGui.QFrame(self.groupBox_14)
        self.frame_26.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_26.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_26.setLineWidth(1)
        self.frame_26.setObjectName("frame_26")
        self.label_39 = QtGui.QLabel(self.frame_26)
        self.label_39.setGeometry(QtCore.QRect(10, 10, 89, 17))
        self.label_39.setObjectName("label_39")
        self.frame_27 = QtGui.QFrame(self.frame_26)
        self.frame_27.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.frame_27.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.label_40 = QtGui.QLabel(self.frame_27)
        self.label_40.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtGui.QLabel(self.frame_27)
        self.label_41.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_41.setObjectName("label_41")
        self.rdist_s_lat_input = QtGui.QLineEdit(self.frame_27)
        self.rdist_s_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.rdist_s_lat_input.setObjectName("rdist_s_lat_input")
        self.rdist_s_lon_input = QtGui.QLineEdit(self.frame_27)
        self.rdist_s_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.rdist_s_lon_input.setObjectName("rdist_s_lon_input")
        self.label_42 = QtGui.QLabel(self.frame_26)
        self.label_42.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.label_42.setObjectName("label_42")
        self.frame_28 = QtGui.QFrame(self.frame_26)
        self.frame_28.setGeometry(QtCore.QRect(10, 190, 351, 81))
        self.frame_28.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.label_43 = QtGui.QLabel(self.frame_28)
        self.label_43.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtGui.QLabel(self.frame_28)
        self.label_44.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_44.setObjectName("label_44")
        self.rdist_d_lat_input = QtGui.QLineEdit(self.frame_28)
        self.rdist_d_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.rdist_d_lat_input.setObjectName("rdist_d_lat_input")
        self.rdist_d_lon_input = QtGui.QLineEdit(self.frame_28)
        self.rdist_d_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.rdist_d_lon_input.setObjectName("rdist_d_lon_input")
        self.widgetTab.addTab(self.tab_7, "")
        self.tab_8 = QtGui.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.groupBox_15 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_15.setGeometry(QtCore.QRect(480, 10, 381, 321))
        self.groupBox_15.setObjectName("groupBox_15")
        self.frame_29 = QtGui.QFrame(self.groupBox_15)
        self.frame_29.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_29.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.rbear_output = QtGui.QTextEdit(self.frame_29)
        self.rbear_output.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.rbear_output.setObjectName("rbear_output")
        self.rbear_ok_btn = QtGui.QPushButton(self.frame_29)
        self.rbear_ok_btn.setGeometry(QtCore.QRect(250, 260, 91, 27))
        self.rbear_ok_btn.setObjectName("rbear_ok_btn")
        self.rbear_clear_btn = QtGui.QPushButton(self.frame_29)
        self.rbear_clear_btn.setGeometry(QtCore.QRect(30, 260, 91, 27))
        self.rbear_clear_btn.setObjectName("rbear_clear_btn")
        self.groupBox_16 = QtGui.QGroupBox(self.tab_8)
        self.groupBox_16.setGeometry(QtCore.QRect(30, 10, 381, 321))
        self.groupBox_16.setObjectName("groupBox_16")
        self.frame_30 = QtGui.QFrame(self.groupBox_16)
        self.frame_30.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_30.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_30.setLineWidth(1)
        self.frame_30.setObjectName("frame_30")
        self.label_45 = QtGui.QLabel(self.frame_30)
        self.label_45.setGeometry(QtCore.QRect(10, 10, 89, 17))
        self.label_45.setObjectName("label_45")
        self.frame_31 = QtGui.QFrame(self.frame_30)
        self.frame_31.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.frame_31.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.label_46 = QtGui.QLabel(self.frame_31)
        self.label_46.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtGui.QLabel(self.frame_31)
        self.label_47.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_47.setObjectName("label_47")
        self.rbear_s_lat_input = QtGui.QLineEdit(self.frame_31)
        self.rbear_s_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.rbear_s_lat_input.setObjectName("rbear_s_lat_input")
        self.rbear_s_lon_input = QtGui.QLineEdit(self.frame_31)
        self.rbear_s_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.rbear_s_lon_input.setObjectName("rbear_s_lon_input")
        self.label_48 = QtGui.QLabel(self.frame_30)
        self.label_48.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.label_48.setObjectName("label_48")
        self.frame_32 = QtGui.QFrame(self.frame_30)
        self.frame_32.setGeometry(QtCore.QRect(10, 190, 351, 81))
        self.frame_32.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.label_49 = QtGui.QLabel(self.frame_32)
        self.label_49.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtGui.QLabel(self.frame_32)
        self.label_50.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_50.setObjectName("label_50")
        self.rbear_d_lat_input = QtGui.QLineEdit(self.frame_32)
        self.rbear_d_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.rbear_d_lat_input.setObjectName("rbear_d_lat_input")
        self.rbear_d_lon_input = QtGui.QLineEdit(self.frame_32)
        self.rbear_d_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.rbear_d_lon_input.setObjectName("rbear_d_lon_input")
        self.widgetTab.addTab(self.tab_8, "")
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.groupBox_17 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_17.setGeometry(QtCore.QRect(30, 10, 381, 321))
        self.groupBox_17.setObjectName("groupBox_17")
        self.frame_37 = QtGui.QFrame(self.groupBox_17)
        self.frame_37.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_37.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_37.setLineWidth(1)
        self.frame_37.setObjectName("frame_37")
        self.label_57 = QtGui.QLabel(self.frame_37)
        self.label_57.setGeometry(QtCore.QRect(10, 10, 89, 17))
        self.label_57.setObjectName("label_57")
        self.frame_38 = QtGui.QFrame(self.frame_37)
        self.frame_38.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.frame_38.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.label_58 = QtGui.QLabel(self.frame_38)
        self.label_58.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtGui.QLabel(self.frame_38)
        self.label_59.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_59.setObjectName("label_59")
        self.rdpoint_s_lat_input = QtGui.QLineEdit(self.frame_38)
        self.rdpoint_s_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.rdpoint_s_lat_input.setObjectName("rdpoint_s_lat_input")
        self.rdpoint_s_lon_input = QtGui.QLineEdit(self.frame_38)
        self.rdpoint_s_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.rdpoint_s_lon_input.setObjectName("rdpoint_s_lon_input")
        self.label_60 = QtGui.QLabel(self.frame_37)
        self.label_60.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.label_60.setObjectName("label_60")
        self.frame_39 = QtGui.QFrame(self.frame_37)
        self.frame_39.setGeometry(QtCore.QRect(10, 190, 351, 81))
        self.frame_39.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.label_61 = QtGui.QLabel(self.frame_39)
        self.label_61.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtGui.QLabel(self.frame_39)
        self.label_62.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_62.setObjectName("label_62")
        self.rdpoint_bear_input = QtGui.QLineEdit(self.frame_39)
        self.rdpoint_bear_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.rdpoint_bear_input.setObjectName("rdpoint_bear_input")
        self.rdpoint_dist_input = QtGui.QLineEdit(self.frame_39)
        self.rdpoint_dist_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.rdpoint_dist_input.setObjectName("rdpoint_dist_input")
        self.groupBox_18 = QtGui.QGroupBox(self.tab_9)
        self.groupBox_18.setGeometry(QtCore.QRect(480, 10, 381, 321))
        self.groupBox_18.setObjectName("groupBox_18")
        self.frame_40 = QtGui.QFrame(self.groupBox_18)
        self.frame_40.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_40.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.rdpoint_output = QtGui.QTextEdit(self.frame_40)
        self.rdpoint_output.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.rdpoint_output.setObjectName("rdpoint_output")
        self.rdpoint_ok_btn = QtGui.QPushButton(self.frame_40)
        self.rdpoint_ok_btn.setGeometry(QtCore.QRect(250, 260, 91, 27))
        self.rdpoint_ok_btn.setObjectName("rdpoint_ok_btn")
        self.rdpoint_clear_btn = QtGui.QPushButton(self.frame_40)
        self.rdpoint_clear_btn.setGeometry(QtCore.QRect(30, 260, 91, 27))
        self.rdpoint_clear_btn.setObjectName("rdpoint_clear_btn")
        self.widgetTab.addTab(self.tab_9, "")
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.groupBox_19 = QtGui.QGroupBox(self.tab_10)
        self.groupBox_19.setGeometry(QtCore.QRect(480, 10, 381, 321))
        self.groupBox_19.setObjectName("groupBox_19")
        self.frame_41 = QtGui.QFrame(self.groupBox_19)
        self.frame_41.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_41.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.rmid_output = QtGui.QTextEdit(self.frame_41)
        self.rmid_output.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.rmid_output.setObjectName("rmid_output")
        self.rmid_ok_btn = QtGui.QPushButton(self.frame_41)
        self.rmid_ok_btn.setGeometry(QtCore.QRect(250, 260, 91, 27))
        self.rmid_ok_btn.setObjectName("rmid_ok_btn")
        self.rmid_clear_btn = QtGui.QPushButton(self.frame_41)
        self.rmid_clear_btn.setGeometry(QtCore.QRect(30, 260, 91, 27))
        self.rmid_clear_btn.setObjectName("rmid_clear_btn")
        self.groupBox_20 = QtGui.QGroupBox(self.tab_10)
        self.groupBox_20.setGeometry(QtCore.QRect(30, 10, 381, 321))
        self.groupBox_20.setObjectName("groupBox_20")
        self.frame_42 = QtGui.QFrame(self.groupBox_20)
        self.frame_42.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_42.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_42.setLineWidth(1)
        self.frame_42.setObjectName("frame_42")
        self.label_63 = QtGui.QLabel(self.frame_42)
        self.label_63.setGeometry(QtCore.QRect(10, 10, 89, 17))
        self.label_63.setObjectName("label_63")
        self.frame_43 = QtGui.QFrame(self.frame_42)
        self.frame_43.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.frame_43.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.label_64 = QtGui.QLabel(self.frame_43)
        self.label_64.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtGui.QLabel(self.frame_43)
        self.label_65.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_65.setObjectName("label_65")
        self.rmid_s_lat_input = QtGui.QLineEdit(self.frame_43)
        self.rmid_s_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.rmid_s_lat_input.setObjectName("rmid_s_lat_input")
        self.rmid_s_lon_input = QtGui.QLineEdit(self.frame_43)
        self.rmid_s_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.rmid_s_lon_input.setObjectName("rmid_s_lon_input")
        self.label_66 = QtGui.QLabel(self.frame_42)
        self.label_66.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.label_66.setObjectName("label_66")
        self.frame_44 = QtGui.QFrame(self.frame_42)
        self.frame_44.setGeometry(QtCore.QRect(10, 190, 351, 81))
        self.frame_44.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.label_67 = QtGui.QLabel(self.frame_44)
        self.label_67.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtGui.QLabel(self.frame_44)
        self.label_68.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_68.setObjectName("label_68")
        self.rmid_d_lat_input = QtGui.QLineEdit(self.frame_44)
        self.rmid_d_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.rmid_d_lat_input.setObjectName("rmid_d_lat_input")
        self.rmid_d_lon_input = QtGui.QLineEdit(self.frame_44)
        self.rmid_d_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.rmid_d_lon_input.setObjectName("rmid_d_lon_input")
        self.widgetTab.addTab(self.tab_10, "")
        self.tab_11 = QtGui.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.groupBox_21 = QtGui.QGroupBox(self.tab_11)
        self.groupBox_21.setGeometry(QtCore.QRect(480, 10, 381, 321))
        self.groupBox_21.setObjectName("groupBox_21")
        self.frame_45 = QtGui.QFrame(self.groupBox_21)
        self.frame_45.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_45.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.dpoint_output = QtGui.QTextEdit(self.frame_45)
        self.dpoint_output.setGeometry(QtCore.QRect(10, 20, 351, 111))
        self.dpoint_output.setObjectName("dpoint_output")
        self.dpoint_ok_btn = QtGui.QPushButton(self.frame_45)
        self.dpoint_ok_btn.setGeometry(QtCore.QRect(250, 260, 91, 27))
        self.dpoint_ok_btn.setObjectName("dpoint_ok_btn")
        self.dpoint_clear_btn = QtGui.QPushButton(self.frame_45)
        self.dpoint_clear_btn.setGeometry(QtCore.QRect(30, 260, 91, 27))
        self.dpoint_clear_btn.setObjectName("dpoint_clear_btn")
        self.groupBox_22 = QtGui.QGroupBox(self.tab_11)
        self.groupBox_22.setGeometry(QtCore.QRect(30, 10, 381, 321))
        self.groupBox_22.setObjectName("groupBox_22")
        self.frame_46 = QtGui.QFrame(self.groupBox_22)
        self.frame_46.setGeometry(QtCore.QRect(0, 20, 371, 301))
        self.frame_46.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_46.setLineWidth(1)
        self.frame_46.setObjectName("frame_46")
        self.label_69 = QtGui.QLabel(self.frame_46)
        self.label_69.setGeometry(QtCore.QRect(10, 10, 89, 17))
        self.label_69.setObjectName("label_69")
        self.frame_47 = QtGui.QFrame(self.frame_46)
        self.frame_47.setGeometry(QtCore.QRect(10, 40, 351, 81))
        self.frame_47.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.label_70 = QtGui.QLabel(self.frame_47)
        self.label_70.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_70.setObjectName("label_70")
        self.label_71 = QtGui.QLabel(self.frame_47)
        self.label_71.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_71.setObjectName("label_71")
        self.dpoint_s_lat_input = QtGui.QLineEdit(self.frame_47)
        self.dpoint_s_lat_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.dpoint_s_lat_input.setObjectName("dpoint_s_lat_input")
        self.dpoint_s_lon_input = QtGui.QLineEdit(self.frame_47)
        self.dpoint_s_lon_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.dpoint_s_lon_input.setObjectName("dpoint_s_lon_input")
        self.label_72 = QtGui.QLabel(self.frame_46)
        self.label_72.setGeometry(QtCore.QRect(10, 160, 121, 17))
        self.label_72.setObjectName("label_72")
        self.frame_48 = QtGui.QFrame(self.frame_46)
        self.frame_48.setGeometry(QtCore.QRect(10, 190, 351, 81))
        self.frame_48.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.label_73 = QtGui.QLabel(self.frame_48)
        self.label_73.setGeometry(QtCore.QRect(10, 50, 71, 17))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtGui.QLabel(self.frame_48)
        self.label_74.setGeometry(QtCore.QRect(10, 13, 71, 17))
        self.label_74.setObjectName("label_74")
        self.dpoint_bear_input = QtGui.QLineEdit(self.frame_48)
        self.dpoint_bear_input.setGeometry(QtCore.QRect(200, 10, 131, 27))
        self.dpoint_bear_input.setObjectName("dpoint_bear_input")
        self.dpoint_dist_input = QtGui.QLineEdit(self.frame_48)
        self.dpoint_dist_input.setGeometry(QtCore.QRect(200, 40, 131, 27))
        self.dpoint_dist_input.setObjectName("dpoint_dist_input")
        self.widgetTab.addTab(self.tab_11, "")
        self.label_75 = QtGui.QLabel(GeoBasic)
        self.label_75.setGeometry(QtCore.QRect(10, 400, 62, 17))
        self.label_75.setObjectName("label_75")
        self.status_output = QtGui.QLabel(GeoBasic)
        self.status_output.setGeometry(QtCore.QRect(60, 400, 711, 17))
        self.status_output.setText("")
        self.status_output.setObjectName("status_output")
        self.cancel_btn = QtGui.QPushButton(GeoBasic)
        self.cancel_btn.setGeometry(QtCore.QRect(790, 400, 91, 27))
        self.cancel_btn.setObjectName("cancel_btn")

        self.retranslateUi(GeoBasic)
        QtCore.QObject.connect(self.cancel_btn , QtCore.SIGNAL("clicked()"), GeoBasic, QtCore.SLOT("close()"))
        QtCore.QObject.connect(self.hav_ok_btn, QtCore.SIGNAL("clicked()"), self.computeDistanceHaversine)
        QtCore.QObject.connect(self.hav_clear_btn, QtCore.SIGNAL("clicked()"), self.clearDistanceHaversine)
        QtCore.QObject.connect(self.sloc_ok_btn, QtCore.SIGNAL("clicked()"), self.computeDistanceSloc)
        QtCore.QObject.connect(self.sloc_clear_btn, QtCore.SIGNAL("clicked()"), self.clearDistanceSloc)
        QtCore.QObject.connect(self.ib_ok_btn, QtCore.SIGNAL("clicked()"), self.computeInitialBearing)
        QtCore.QObject.connect(self.ib_clear_btn, QtCore.SIGNAL("clicked()"), self.clearInitialBearing)
        QtCore.QObject.connect(self.fb_ok_btn, QtCore.SIGNAL("clicked()"), self.computeFinalBearing)
        QtCore.QObject.connect(self.fb_clear_btn, QtCore.SIGNAL("clicked()"), self.clearFinalBearing)
        QtCore.QObject.connect(self.mid_ok_btn, QtCore.SIGNAL("clicked()"), self.computeMidpoint)
        QtCore.QObject.connect(self.mid_clear_btn, QtCore.SIGNAL("clicked()"), self.clearMidpoint)
        QtCore.QObject.connect(self.int_ok_btn, QtCore.SIGNAL("clicked()"), self.computeIntersection)
        QtCore.QObject.connect(self.int_clear_btn, QtCore.SIGNAL("clicked()"), self.clearIntersection)
        QtCore.QObject.connect(self.rdist_ok_btn, QtCore.SIGNAL("clicked()"), self.computeRhumbDistance)
        QtCore.QObject.connect(self.rdist_clear_btn, QtCore.SIGNAL("clicked()"), self.clearRhumbDistance)
        QtCore.QObject.connect(self.rbear_ok_btn, QtCore.SIGNAL("clicked()"), self.computeRhumbBearing)
        QtCore.QObject.connect(self.rbear_clear_btn, QtCore.SIGNAL("clicked()"), self.clearRhumbBearing)
        QtCore.QObject.connect(self.rdpoint_ok_btn, QtCore.SIGNAL("clicked()"), self.computeRhumbDestinationPoint)
        QtCore.QObject.connect(self.rdpoint_clear_btn, QtCore.SIGNAL("clicked()"), self.clearRhumbDestinationPoint)
        QtCore.QObject.connect(self.rmid_ok_btn, QtCore.SIGNAL("clicked()"), self.computeRhumbMidpoint)
        QtCore.QObject.connect(self.rmid_clear_btn, QtCore.SIGNAL("clicked()"), self.clearRhumbMidpoint)
        QtCore.QObject.connect(self.dpoint_ok_btn, QtCore.SIGNAL("clicked()"), self.computeDestinationPoint)
        QtCore.QObject.connect(self.dpoint_clear_btn, QtCore.SIGNAL("clicked()"), self.clearDestinationPoint)
        self.widgetTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GeoBasic)

    def retranslateUi(self, GeoBasic):
        GeoBasic.setWindowTitle(QtGui.QApplication.translate("GeoBasic", "Geo Services", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("GeoBasic", "Input parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("GeoBasic", "Source point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("GeoBasic", "Destination point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("GeoBasic", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.hav_ok_btn.setText(QtGui.QApplication.translate("GeoBasic", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.hav_clear_btn.setText(QtGui.QApplication.translate("GeoBasic", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetTab.setTabText(self.widgetTab.indexOf(self.tab), QtGui.QApplication.translate("GeoBasic", "Distance haversine", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("GeoBasic", "Input parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("GeoBasic", "Source point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("GeoBasic", "Destination point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("GeoBasic", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.sloc_ok_btn.setText(QtGui.QApplication.translate("GeoBasic", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.sloc_clear_btn.setText(QtGui.QApplication.translate("GeoBasic", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetTab.setTabText(self.widgetTab.indexOf(self.tab_2), QtGui.QApplication.translate("GeoBasic", "Distance sloc", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("GeoBasic", "Input parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("GeoBasic", "Source point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("GeoBasic", "Destination point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("GeoBasic", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.ib_ok_btn.setText(QtGui.QApplication.translate("GeoBasic", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.ib_clear_btn.setText(QtGui.QApplication.translate("GeoBasic", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetTab.setTabText(self.widgetTab.indexOf(self.tab_3), QtGui.QApplication.translate("GeoBasic", "Initial bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("GeoBasic", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.fb_ok_btn.setText(QtGui.QApplication.translate("GeoBasic", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.fb_clear_btn.setText(QtGui.QApplication.translate("GeoBasic", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("GeoBasic", "Input parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("GeoBasic", "Source point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("GeoBasic", "Destination point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetTab.setTabText(self.widgetTab.indexOf(self.tab_4), QtGui.QApplication.translate("GeoBasic", "Final bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("GeoBasic", "Input parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("GeoBasic", "Source point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("GeoBasic", "Destination point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("GeoBasic", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.mid_ok_btn.setText(QtGui.QApplication.translate("GeoBasic", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.mid_clear_btn.setText(QtGui.QApplication.translate("GeoBasic", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetTab.setTabText(self.widgetTab.indexOf(self.tab_5), QtGui.QApplication.translate("GeoBasic", "Midpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("GeoBasic", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.int_ok_btn.setText(QtGui.QApplication.translate("GeoBasic", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.int_clear_btn.setText(QtGui.QApplication.translate("GeoBasic", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("GeoBasic", "Input parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("GeoBasic", "Source point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("GeoBasic", "Bearing:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("GeoBasic", "Destination point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("GeoBasic", "Bearing:", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetTab.setTabText(self.widgetTab.indexOf(self.tab_6), QtGui.QApplication.translate("GeoBasic", "Intersection", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("GeoBasic", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.rdist_ok_btn.setText(QtGui.QApplication.translate("GeoBasic", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.rdist_clear_btn.setText(QtGui.QApplication.translate("GeoBasic", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_14.setTitle(QtGui.QApplication.translate("GeoBasic", "Input parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("GeoBasic", "Source point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("GeoBasic", "Destination point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetTab.setTabText(self.widgetTab.indexOf(self.tab_7), QtGui.QApplication.translate("GeoBasic", "Rhumb distance", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_15.setTitle(QtGui.QApplication.translate("GeoBasic", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.rbear_ok_btn.setText(QtGui.QApplication.translate("GeoBasic", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.rbear_clear_btn.setText(QtGui.QApplication.translate("GeoBasic", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_16.setTitle(QtGui.QApplication.translate("GeoBasic", "Input parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("GeoBasic", "Source point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_47.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_48.setText(QtGui.QApplication.translate("GeoBasic", "Destination point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetTab.setTabText(self.widgetTab.indexOf(self.tab_8), QtGui.QApplication.translate("GeoBasic", "Rhumb bearing", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_17.setTitle(QtGui.QApplication.translate("GeoBasic", "Input parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_57.setText(QtGui.QApplication.translate("GeoBasic", "Source point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("GeoBasic", "Additional params", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("GeoBasic", "Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("GeoBasic", "Bearing:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_18.setTitle(QtGui.QApplication.translate("GeoBasic", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.rdpoint_ok_btn.setText(QtGui.QApplication.translate("GeoBasic", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.rdpoint_clear_btn.setText(QtGui.QApplication.translate("GeoBasic", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetTab.setTabText(self.widgetTab.indexOf(self.tab_9), QtGui.QApplication.translate("GeoBasic", "Rhumb destination point", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_19.setTitle(QtGui.QApplication.translate("GeoBasic", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.rmid_ok_btn.setText(QtGui.QApplication.translate("GeoBasic", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.rmid_clear_btn.setText(QtGui.QApplication.translate("GeoBasic", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_20.setTitle(QtGui.QApplication.translate("GeoBasic", "Input parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("GeoBasic", "Source point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_65.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_66.setText(QtGui.QApplication.translate("GeoBasic", "Destination point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_67.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_68.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetTab.setTabText(self.widgetTab.indexOf(self.tab_10), QtGui.QApplication.translate("GeoBasic", "Rhumb midpoint", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_21.setTitle(QtGui.QApplication.translate("GeoBasic", "Output parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.dpoint_ok_btn.setText(QtGui.QApplication.translate("GeoBasic", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.dpoint_clear_btn.setText(QtGui.QApplication.translate("GeoBasic", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_22.setTitle(QtGui.QApplication.translate("GeoBasic", "Input parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_69.setText(QtGui.QApplication.translate("GeoBasic", "Source point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_70.setText(QtGui.QApplication.translate("GeoBasic", "Longitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_71.setText(QtGui.QApplication.translate("GeoBasic", "Latitude:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("GeoBasic", "Additional params", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("GeoBasic", "Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_74.setText(QtGui.QApplication.translate("GeoBasic", "Bearing:", None, QtGui.QApplication.UnicodeUTF8))
        self.widgetTab.setTabText(self.widgetTab.indexOf(self.tab_11), QtGui.QApplication.translate("GeoBasic", "Destination point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("GeoBasic", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_btn.setText(QtGui.QApplication.translate("GeoBasic", "Cancel", None, QtGui.QApplication.UnicodeUTF8))


    def computeDistanceHaversine(self):
        ''' 
        @brief This function is used to compute distance using haversine formula.
        @param None
        @return This function does not return a value. 
        '''
        try:
            lat1 = float(self.hav_s_lat_input.text())
            lon1 = float(self.hav_s_lon_input.text())
            lat2 = float(self.hav_d_lat_input.text())
            lon2 = float(self.hav_d_lon_input.text())
            
            #Compute distance.
            distance = self.client_distance_haversine(lat1, lon1, lat2, lon2)
            #First clear textBox content.
            self.hav_output.clear()
            #Display results on textBox.
            self.hav_output.append("<font color='green'>Distance (in km): </font>%f" % (distance))
            #Set status to OK state.
            self.status_output.setText('OK')
        except ValueError:
            err_type, err_value, err_traceback = sys.exc_info()
            self.status_output.setText('Error: %s' % (err_value))
            print('Error type: %s' % (err_type))
            print('Error value: %s' % (err_value))
            print('Error traceback: %s' % (err_traceback))
            
    def clearDistanceHaversine(self):
        '''
        @brief This function is used to clear all fields in 'Distance haversine' tab.
        @param None
        @return This function does not return a value.
        '''
        self.hav_s_lat_input.clear()
        self.hav_s_lon_input.clear()
        self.hav_d_lat_input.clear()
        self.hav_d_lon_input.clear()
        self.hav_output.clear()
        #Status also.
        self.status_output.clear()
        
    def computeDistanceSloc(self):
        ''' 
        @brief This function is used to compute distance using sloc formula.
        @param None
        @return This function does not return a value. 
        '''
        try:
            lat1 = float(self.sloc_s_lat_input.text())
            lon1 = float(self.sloc_s_lon_input.text())
            lat2 = float(self.sloc_d_lat_input.text())
            lon2 = float(self.sloc_d_lon_input.text())
            
            #Compute distance.
            distance = self.client_distance_sloc(lat1, lon1, lat2, lon2)
            #First clear textBox content.
            self.sloc_output.clear()
            #Display results on textBox.
            self.sloc_output.append("<font color='green'>Distance (in km): </font>%f" % (distance))
            #Set status to OK state.
            self.status_output.setText('OK')
        except ValueError:
            err_type, err_value, err_traceback = sys.exc_info()
            self.status_output.setText('Error: %s' % (err_value))
            print('Error type: %s' % (err_type))
            print('Error value: %s' % (err_value))
            print('Error traceback: %s' % (err_traceback))
            
    def clearDistanceSloc(self):
        '''
        @brief This function is used to clear all fields in 'Distance sloc' tab.
        @param None
        @return This function does not return a value.
        '''
        self.sloc_s_lat_input.clear()
        self.sloc_s_lon_input.clear()
        self.sloc_d_lat_input.clear()
        self.sloc_d_lon_input.clear()
        self.sloc_output.clear()
        #Status also.
        self.status_output.clear()
        
        
    def computeInitialBearing(self):
        ''' 
        @brief This function is used to compute initial bearing.
        @param None
        @return This function does not return a value. 
        '''
        try:
            lat1 = float(self.ib_s_lat_input.text())
            lon1 = float(self.ib_s_lon_input.text())
            lat2 = float(self.ib_d_lat_input.text())
            lon2 = float(self.ib_d_lon_input.text())
            
            #Compute bearing.
            bearing = self.client_initial_bearing(lat1, lon1, lat2, lon2)
            #First clear textBox content.
            self.ib_output.clear()
            #Display results on textBox.
            self.ib_output.append("<font color='green'>Initial bearing: </font>%f" % (bearing))
            #Set status to OK state.
            self.status_output.setText('OK')
        except ValueError:
            err_type, err_value, err_traceback = sys.exc_info()
            self.status_output.setText('Error: %s' % (err_value))
            print('Error type: %s' % (err_type))
            print('Error value: %s' % (err_value))
            print('Error traceback: %s' % (err_traceback))
            
    def clearInitialBearing(self):
        '''
        @brief This function is used to clear all fields in 'Initial Bearing' tab.
        @param None
        @return This function does not return a value.
        '''
        self.ib_s_lat_input.clear()
        self.ib_s_lon_input.clear()
        self.ib_d_lat_input.clear()
        self.ib_d_lon_input.clear()
        self.ib_output.clear()
        #Status also.
        self.status_output.clear()
        
    def computeFinalBearing(self):
        ''' 
        @brief This function is used to compute final bearing.
        @param None
        @return This function does not return a value. 
        '''
        try:
            lat1 = float(self.fb_s_lat_input.text())
            lon1 = float(self.fb_s_lon_input.text())
            lat2 = float(self.fb_d_lat_input.text())
            lon2 = float(self.fb_d_lon_input.text())
            
            #Compute bearing.
            bearing = self.client_final_bearing(lat1, lon1, lat2, lon2)
            #First clear textBox content.
            self.fb_output.clear()
            #Display results on textBox.
            self.fb_output.append("<font color='green'>Final bearing: </font>%f" % (bearing))
            #Set status to OK state.
            self.status_output.setText('OK')
        except ValueError:
            err_type, err_value, err_traceback = sys.exc_info()
            self.status_output.setText('Error: %s' % (err_value))
            print('Error type: %s' % (err_type))
            print('Error value: %s' % (err_value))
            print('Error traceback: %s' % (err_traceback))
            
    def clearFinalBearing(self):
        '''
        @brief This function is used to clear all fields in 'Final Bearing' tab.
        @param None
        @return This function does not return a value.
        '''
        self.fb_s_lat_input.clear()
        self.fb_s_lon_input.clear()
        self.fb_d_lat_input.clear()
        self.fb_d_lon_input.clear()
        self.fb_output.clear()
        #Status also.
        self.status_output.clear()
        
    def computeMidpoint(self):
        ''' 
        @brief This function is used to compute midpoint between two points.
        @param None
        @return This function does not return a value. 
        '''
        try:
            lat1 = float(self.mid_s_lat_input.text())
            lon1 = float(self.mid_s_lon_input.text())
            lat2 = float(self.mid_d_lat_input.text())
            lon2 = float(self.mid_d_lon_input.text())
            
            #Compute midpoint.
            midpoint = self.client_midpoint(lat1, lon1, lat2, lon2)
            #First clear textBox content.
            self.mid_output.clear()
            #Display results on textBox.
            self.mid_output.append("<font color='green'>Midpoint coordinates </font>")
            self.mid_output.append("<font color='green'>Latitude: </font>%s" % (midpoint.lat))
            self.mid_output.append("<font color='green'>Longitude: </font>%s" % (midpoint.lon))
            #Set status to OK state.
            self.status_output.setText('OK')
        except ValueError:
            err_type, err_value, err_traceback = sys.exc_info()
            self.status_output.setText('Error: %s' % (err_value))
            print('Error type: %s' % (err_type))
            print('Error value: %s' % (err_value))
            print('Error traceback: %s' % (err_traceback))
            
    def clearMidpoint(self):
        '''
        @brief This function is used to clear all fields in 'Midpoint' tab.
        @param None
        @return This function does not return a value.
        '''
        self.mid_s_lat_input.clear()
        self.mid_s_lon_input.clear()
        self.mid_d_lat_input.clear()
        self.mid_d_lon_input.clear()
        self.mid_output.clear()
        #Status also.
        self.status_output.clear()
        
    def computeIntersection(self):
        ''' 
        @brief This function is used to compute intersection between two paths.
        @param None
        @return This function does not return a value. 
        '''
        try:
            lat1 = float(self.int_s_lat_input.text())
            lon1 = float(self.int_s_lon_input.text())
            brng1 = float(self.int_s_bear_input.text())
            lat2 = float(self.int_d_lat_input.text())
            lon2 = float(self.int_d_lon_input.text())
            brng2 = float(self.int_d_bear_input.text())
            
            #Compute intersection.
            intersection = self.client_intersection(lat1, lon1, brng1, lat2, lon2, brng2)
            #First clear textBox content.
            self.int_output.clear()
            #Display results on textBox.
            self.int_output.append("<font color='green'>Intersection point coordinates </font>")
            self.int_output.append("<font color='green'>Latitude: </font>%s" % (intersection.lat))
            self.int_output.append("<font color='green'>Longitude: </font>%s" % (intersection.lon))
            #Set status to OK state.
            self.status_output.setText('OK')
        except ValueError:
            err_type, err_value, err_traceback = sys.exc_info()
            self.status_output.setText('Error: %s' % (err_value))
            print('Error type: %s' % (err_type))
            print('Error value: %s' % (err_value))
            print('Error traceback: %s' % (err_traceback))
            
    def clearIntersection(self):
        '''
        @brief This function is used to clear all fields in 'Intersection' tab.
        @param None
        @return This function does not return a value.
        '''
        self.int_s_lat_input.clear()
        self.int_s_lon_input.clear()
        self.int_s_bear_input.clear()
        self.int_d_lat_input.clear()
        self.int_d_lon_input.clear()
        self.int_d_bear_input.clear()
        self.int_output.clear()
        #Status also.
        self.status_output.clear()
        
    def computeRhumbDistance(self):
        ''' 
        @brief This function is used to compute rhumb distance between two points.
        @param None
        @return This function does not return a value. 
        '''
        try:
            lat1 = float(self.rdist_s_lat_input.text())
            lon1 = float(self.rdist_s_lon_input.text())
            lat2 = float(self.rdist_d_lat_input.text())
            lon2 = float(self.rdist_d_lon_input.text())
            
            #Compute rhumb distance.
            distance = self.client_rhumb_distance(lat1, lon1, lat2, lon2)
            #First clear textBox content.
            self.rdist_output.clear()
            #Display results on textBox.
            self.rdist_output.append("<font color='green'>Rhumb distance (in km): </font>%f" % (distance))
            #Set status to OK state.
            self.status_output.setText('OK')
        except ValueError:
            err_type, err_value, err_traceback = sys.exc_info()
            self.status_output.setText('Error: %s' % (err_value))
            print('Error type: %s' % (err_type))
            print('Error value: %s' % (err_value))
            print('Error traceback: %s' % (err_traceback))
            
    def clearRhumbDistance(self):
        '''
        @brief This function is used to clear all fields in 'Rhumb distance' tab.
        @param None
        @return This function does not return a value.
        '''
        self.rdist_s_lat_input.clear()
        self.rdist_s_lon_input.clear()
        self.rdist_d_lat_input.clear()
        self.rdist_d_lon_input.clear()
        self.rdist_output.clear()
        #Status also.
        self.status_output.clear()
        
    def computeRhumbBearing(self):
        ''' 
        @brief This function is used to compute rhumb bearing between two points.
        @param None
        @return This function does not return a value. 
        '''
        try:
            lat1 = float(self.rbear_s_lat_input.text())
            lon1 = float(self.rbear_s_lon_input.text())
            lat2 = float(self.rbear_d_lat_input.text())
            lon2 = float(self.rbear_d_lon_input.text())
            
            #Compute rhumb bearing.
            bearing = self.client_rhumb_bearing(lat1, lon1, lat2, lon2)
            #First clear textBox content.
            self.rbear_output.clear()
            #Display results on textBox.
            self.rbear_output.append("<font color='green'>Rhumb bearing: </font>%f" % (bearing))
            #Set status to OK state.
            self.status_output.setText('OK')
        except ValueError:
            err_type, err_value, err_traceback = sys.exc_info()
            self.status_output.setText('Error: %s' % (err_value))
            print('Error type: %s' % (err_type))
            print('Error value: %s' % (err_value))
            print('Error traceback: %s' % (err_traceback))
            
    def clearRhumbBearing(self):
        '''
        @brief This function is used to clear all fields in 'Rhumb bearing' tab.
        @param None
        @return This function does not return a value.
        '''
        self.rbear_s_lat_input.clear()
        self.rbear_s_lon_input.clear()
        self.rbear_d_lat_input.clear()
        self.rbear_d_lon_input.clear()
        self.rbear_output.clear()
        #Status also.
        self.status_output.clear()
        
    def computeRhumbDestinationPoint(self):
        ''' 
        @brief This function is used to compute rhumb destination point.
        @param None
        @return This function does not return a value. 
        '''
        try:
            lat1 = float(self.rdpoint_s_lat_input.text())
            lon1 = float(self.rdpoint_s_lon_input.text())
            brng = float(self.rdpoint_bear_input.text())
            dist = float(self.rdpoint_dist_input.text())
            
            #Compute rhumb destination point.
            rdpoint = self.client_rhumb_destination_point(lat1, lon1, brng, dist)
            #First clear textBox content.
            self.dpoint_output.clear()
            #Display results on textBox.
            self.rdpoint_output.append("<font color='green'>Destination point </font>")
            self.rdpoint_output.append("<font color='green'>Latitude: </font>%s" % (rdpoint.lat))
            self.rdpoint_output.append("<font color='green'>Longitude: </font>%s" % (rdpoint.lon))
            #Set status to OK state.
            self.status_output.setText('OK')
        except ValueError:
            err_type, err_value, err_traceback = sys.exc_info()
            self.status_output.setText('Error: %s' % (err_value))
            print('Error type: %s' % (err_type))
            print('Error value: %s' % (err_value))
            print('Error traceback: %s' % (err_traceback))
            
    def clearRhumbDestinationPoint(self):
        '''
        @brief This function is used to clear all fields in 'Rhumb destination point' tab.
        @param None
        @return This function does not return a value.
        '''
        self.rdpoint_s_lat_input.clear()
        self.rdpoint_s_lon_input.clear()
        self.rdpoint_bear_input.clear()
        self.rdpoint_dist_input.clear()
        self.rdpoint_output.clear()
        #Status also.
        self.status_output.clear()
        
    def computeRhumbMidpoint(self):
        ''' 
        @brief This function is used to compute rhumb midpoint between two points.
        @param None
        @return This function does not return a value. 
        '''
        try:
            lat1 = float(self.rmid_s_lat_input.text())
            lon1 = float(self.rmid_s_lon_input.text())
            lat2 = float(self.rmid_d_lat_input.text())
            lon2 = float(self.rmid_d_lon_input.text())
            
            #Compute rhumb midpoint.
            midpoint = self.client_rhumb_midpoint(lat1, lon1, lat2, lon2)
            #First clear textBox content.
            self.rmid_output.clear()
            #Display results on textBox.
            self.rmid_output.append("<font color='green'>Midpoint coordinates </font>")
            self.rmid_output.append("<font color='green'>Latitude: </font>%s" % (midpoint.lat))
            self.rmid_output.append("<font color='green'>Longitude: </font>%s" % (midpoint.lon))
            #Set status to OK state.
            self.status_output.setText('OK')
        except ValueError:
            err_type, err_value, err_traceback = sys.exc_info()
            self.status_output.setText('Error: %s' % (err_value))
            print('Error type: %s' % (err_type))
            print('Error value: %s' % (err_value))
            print('Error traceback: %s' % (err_traceback))
            
    def clearRhumbMidpoint(self):
        '''
        @brief This function is used to clear all fields in 'Rhumb midpoint' tab.
        @param None
        @return This function does not return a value.
        '''
        self.rmid_s_lat_input.clear()
        self.rmid_s_lon_input.clear()
        self.rmid_d_lat_input.clear()
        self.rmid_d_lon_input.clear()
        self.rmid_output.clear()
        #Status also.
        self.status_output.clear()
        
    def computeDestinationPoint(self):
        ''' 
        @brief This function is used to compute destination point.
        @param None
        @return This function does not return a value. 
        '''
        try:
            lat1 = float(self.dpoint_s_lat_input.text())
            lon1 = float(self.dpoint_s_lon_input.text())
            brng = float(self.dpoint_bear_input.text())
            dist = float(self.dpoint_dist_input.text())
            
            #Compute destination point.
            dpoint = self.client_destination_point(lat1, lon1, brng, dist)
            #First clear textBox content.
            self.dpoint_output.clear()
            #Display results on textBox.
            self.dpoint_output.append("<font color='green'>Destination point </font>")
            self.dpoint_output.append("<font color='green'>Latitude: </font>%s" % (dpoint.lat))
            self.dpoint_output.append("<font color='green'>Longitude: </font>%s" % (dpoint.lon))
            #Set status to OK state.
            self.status_output.setText('OK')
        except ValueError:
            err_type, err_value, err_traceback = sys.exc_info()
            self.status_output.setText('Error: %s' % (err_value))
            print('Error type: %s' % (err_type))
            print('Error value: %s' % (err_value))
            print('Error traceback: %s' % (err_traceback))
            
    def clearDestinationPoint(self):
        '''
        @brief This function is used to clear all fields in 'Destination point' tab.
        @param None
        @return This function does not return a value.
        '''
        self.dpoint_s_lat_input.clear()
        self.dpoint_s_lon_input.clear()
        self.dpoint_bear_input.clear()
        self.dpoint_dist_input.clear()
        self.dpoint_output.clear()
        #Status also.
        self.status_output.clear()