# DO NOT EDIT THIS FILE!
#
# Python module Raster__POA generated by omniidl

import omniORB
omniORB.updateModule("Raster__POA")

# ** 1. Stub files contributing to this module
import raster_idl

# ** 2. Sub-modules

# ** 3. End
