.TH "/home/bartek/git/SpatialAnalyserServer/SpatialAnalyserServer/database/postgres/Basic.py" 3 "18 Jun 2012" "Version 1.0.0" "SpatialAnalyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/bartek/git/SpatialAnalyserServer/SpatialAnalyserServer/database/postgres/Basic.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdatabase::postgres::Basic::PostgresBasic\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBdatabase::postgres::Basic\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBdatabase::postgres::Basic::test\fP = PostgresBasic()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SpatialAnalyzer from the source code.
