.TH "/home/bartek/git/SpatialAnalyserServer/SpatialAnalyserServer/src/client/gui/client_main.py" 3 "18 Jun 2012" "Version 1.0.0" "SpatialAnalyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/bartek/git/SpatialAnalyserServer/SpatialAnalyserServer/src/client/gui/client_main.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc::client::gui::client_main::Ui_MainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc::client::gui::client_main\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SpatialAnalyzer from the source code.
