.TH "/home/bartek/git/SpatialAnalyserServer/SpatialAnalyserServer/src/client/gui/splash_screen.py" 3 "18 Jun 2012" "Version 1.0.0" "SpatialAnalyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/bartek/git/SpatialAnalyserServer/SpatialAnalyserServer/src/client/gui/splash_screen.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsrc::client::gui::splash_screen::Splash\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsrc::client::gui::splash_screen\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBsrc::client::gui::splash_screen::splash\fP = Splash()"
.br
.ti -1c
.RI "tuple \fBsrc::client::gui::splash_screen::app\fP = QtGui.QApplication(sys.argv)"
.br
.ti -1c
.RI "tuple \fBsrc::client::gui::splash_screen::MainWindow\fP = QtGui.QMainWindow()"
.br
.ti -1c
.RI "tuple \fBsrc::client::gui::splash_screen::ui\fP = client_main.Ui_MainWindow()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SpatialAnalyzer from the source code.
