.TH "src::client::gui::splash_screen" 3 "18 Jun 2012" "Version 1.0.0" "SpatialAnalyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src::client::gui::splash_screen \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSplash\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBsplash\fP = \fBSplash\fP()"
.br
.ti -1c
.RI "tuple \fBapp\fP = QtGui.QApplication(sys.argv)"
.br
.ti -1c
.RI "tuple \fBMainWindow\fP = QtGui.QMainWindow()"
.br
.ti -1c
.RI "tuple \fBui\fP = \fBclient_main.Ui_MainWindow\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple \fBsrc::client::gui::splash_screen::app\fP = QtGui.QApplication(sys.argv)"
.PP
Definition at line 33 of file splash_screen.py.
.SS "tuple \fBsrc::client::gui::splash_screen::MainWindow\fP = QtGui.QMainWindow()"
.PP
Definition at line 36 of file splash_screen.py.
.SS "tuple \fBsrc::client::gui::splash_screen::splash\fP = \fBSplash\fP()"
.PP
Definition at line 32 of file splash_screen.py.
.SS "tuple \fBsrc::client::gui::splash_screen::ui\fP = \fBclient_main.Ui_MainWindow\fP()"
.PP
Definition at line 37 of file splash_screen.py.
.SH "Author"
.PP 
Generated automatically by Doxygen for SpatialAnalyzer from the source code.
