.TH "src::client" 3 "18 Jun 2012" "Version 1.0.0" "SpatialAnalyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src::client \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBClient\fP"
.br
.ti -1c
.RI "namespace \fBgui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SpatialAnalyzer from the source code.
