.TH "src::client::gui::client_gui" 3 "18 Jun 2012" "Version 1.0.0" "SpatialAnalyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src::client::gui::client_gui \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBapp\fP = QtGui.QApplication(sys.argv)"
.br
.ti -1c
.RI "tuple \fBMainWindow\fP = QtGui.QMainWindow()"
.br
.ti -1c
.RI "tuple \fBui\fP = \fBclient_main.Ui_MainWindow\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple \fBsrc::client::gui::client_gui::app\fP = QtGui.QApplication(sys.argv)"
.PP
Definition at line 9 of file client_gui.py.
.SS "tuple \fBsrc::client::gui::client_gui::MainWindow\fP = QtGui.QMainWindow()"
.PP
Definition at line 10 of file client_gui.py.
.SS "tuple \fBsrc::client::gui::client_gui::ui\fP = \fBclient_main.Ui_MainWindow\fP()"
.PP
Definition at line 11 of file client_gui.py.
.SH "Author"
.PP 
Generated automatically by Doxygen for SpatialAnalyzer from the source code.
