.TH "src::client::gui::draw_from_osm" 3 "18 Jun 2012" "Version 1.0.0" "SpatialAnalyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src::client::gui::draw_from_osm \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_DrawFromOSMFile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.PP
.nf

Created on Jun 16, 2012

@author: bartek
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for SpatialAnalyzer from the source code.
