.TH "src::client::gui::splash_screen::Splash" 3 "18 Jun 2012" "Version 1.0.0" "SpatialAnalyzer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src::client::gui::splash_screen::Splash \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBshow_splash\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconfSplashImageLoc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file splash_screen.py.
.SH "Member Function Documentation"
.PP 
.SS "def src::client::gui::splash_screen::Splash::__init__ ( self)"
.PP
Definition at line 6 of file splash_screen.py.
.SS "def src::client::gui::splash_screen::Splash::show_splash ( self,  path)"
.PP
Definition at line 13 of file splash_screen.py.
.SH "Member Data Documentation"
.PP 
.SS "\fBsrc::client::gui::splash_screen::Splash::confSplashImageLoc\fP"
.PP
Definition at line 11 of file splash_screen.py.

.SH "Author"
.PP 
Generated automatically by Doxygen for SpatialAnalyzer from the source code.
