module SHPDraw {
	typedef string <1024> DirPath;	
	
    typedef string <1024> FileName;
	typedef string <1024> Created;
	typedef string <1024> LastModified;

	struct File {
		FileName fName;
		Created  cTime;
		LastModified lModified;
	};

	typedef sequence<File> FileList;
	typedef sequence<octet> FileContent;

	exception UnknownInternalError {
		string reason;
	};
	exception FileNotFound {
		string reason;
		string fileName;
	};

	interface Basic {
		attribute string dirLocation;
		FileList get_shp_file_list() raises (UnknownInternalError);
		FileContent get_shp_file_content(in string fileName) raises (FileNotFound);

		FileList get_osm_file_list() raises (UnknownInternalError);
		FileContent get_osm_file_content(in string fileName) raises (FileNotFound);
		string draw_osm_file(in string fileName, in long width, in long height) raises (FileNotFound);
	};
};
