module SHP {

	typedef string<1024> ip;
	typedef string<1024> db;
	typedef string<1024> user;

	struct dbParams {
		ip db_ip;
		db db_name;
		user db_user;
	};
	exception FileDoesNotExist { 
		string reason;
		string fileName;
	};

	exception CannotConnectToDB {
		string reason;
		string dbName;
	};

	interface ShpToDB {
		dbParams send_shp_to_postgres(in string shp_file, in string table_name) raises (FileDoesNotExist, CannotConnectToDB);

		void send_wbd_to_postgres(in string shp_file) raises (FileDoesNotExist, CannotConnectToDB);
	};
};
