# DO NOT EDIT THIS FILE!
#
# Python module Projection generated by omniidl

import omniORB
omniORB.updateModule("Projection")

# ** 1. Stub files contributing to this module
import geodetic_computation_idl

# ** 2. Sub-modules

# ** 3. End
