# DO NOT EDIT THIS FILE!
#
# Python module Info generated by omniidl

import omniORB
omniORB.updateModule("Info")

# ** 1. Stub files contributing to this module
import raster_info_idl

# ** 2. Sub-modules

# ** 3. End
