# DO NOT EDIT THIS FILE!
#
# Python module Raster generated by omniidl

import omniORB
omniORB.updateModule("Raster")

# ** 1. Stub files contributing to this module
import raster_idl

# ** 2. Sub-modules

# ** 3. End
