# DO NOT EDIT THIS FILE!
#
# Python module Geo__POA generated by omniidl

import omniORB
omniORB.updateModule("Geo__POA")

# ** 1. Stub files contributing to this module
import geo_idl

# ** 2. Sub-modules

# ** 3. End
