# DO NOT EDIT THIS FILE!
#
# Python module SHPDraw__POA generated by omniidl

import omniORB
omniORB.updateModule("SHPDraw__POA")

# ** 1. Stub files contributing to this module
import shp_draw_idl

# ** 2. Sub-modules

# ** 3. End
