# DO NOT EDIT THIS FILE!
#
# Python module DB generated by omniidl

import omniORB
omniORB.updateModule("DB")

# ** 1. Stub files contributing to this module
import db_shp_idl

# ** 2. Sub-modules

# ** 3. End
