# DO NOT EDIT THIS FILE!
#
# Python module SHP__POA generated by omniidl

import omniORB
omniORB.updateModule("SHP__POA")

# ** 1. Stub files contributing to this module
import shp_to_db_idl

# ** 2. Sub-modules

# ** 3. End
